CREATE TABLE TVListings (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  date DATE NULL,
  PRIMARY KEY(id)
);
CREATE TABLE Shows (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  id_listing INTEGER UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NULL,
  tvrageLink VARCHAR(255) NULL,
  airTime TIME NOT NULL,
  PRIMARY KEY(id),
  INDEX Shows_FKIndex1(id_listing)
);